### ISSUE TITLE
[C# 6.0] Перенос работы на новую студию

### ISSUE THREAD

**Issue by ViIvanov** [rsdn/janus#1]
// Надеюсь, можно тут по-русски?

Пара вопросов:
1. Нет ли планов перенести разработку на новую студию и использовать шестой шарп? Переход на новый фреймворк не принципиален.
2. Если нужно, могу допилить драг-дроп, смотрю его закоментарили до лучших времён: https://github.com/rsdn/janus/blob/d28a924a66c1ebd4f88415abca37b901d819e321/Janus/Core/Navigation/NavigationDummyForm.cs#L393, но нужно обсудить, в какую сторону делать, что обобщать.

**Comment by andrewvk** [comment]
Можно и перевести, особых препятствий нет.

Допиливай, если есть желание. Хотя, на мой вкус, особой нужды в нем нет.

Sent from Surface

From: Viacheslav Ivanov
Sent: ‎Wednesday‎, ‎July‎ ‎22‎, ‎2015 ‎8‎:‎09‎ ‎AM
To: rsdn/janus

// Надеюсь, можно тут по-русски?

Пара вопросов:
1. Нет ли планов перенести разработку на новую студию и использовать шестой шарп? Переход на новый фреймворк не принципиален.
2. Если нужно, могу допилить драг-дроп, смотрю его закоментарили до лучших времён: https://github.com/rsdn/janus/blob/d28a924a66c1ebd4f88415abca37b901d819e321/Janus/Core/Navigation/NavigationDummyForm.cs#L393, но нужно обсудить, в какую сторону делать, что обобщать.

**Comment by ViIvanov** [comment]
Ага, это в первую очередь for fun.

Не расскажешь, какие идеи были по генерализации?
Имелось в виду то, что логику надо вынести в NavigationTreeNode? https://github.com/rsdn/janus/blob/d28a924a66c1ebd4f88415abca37b901d819e321/Janus-Common/CoreServices/NavigationTree/NavigationTreeNode.cs#L77

Ещё какие-то пожелания будут?

**Comment by andrewvk** [comment]
Я не знаю, я туда даже не смотрел ни разу.

2015-07-22 10:14 GMT+03:00 Viacheslav Ivanov notifications@github.com:

> Ага, это в первую очередь for fun.
> 
> Не расскажешь, какие идеи были по генерализации?
> Имелось в виду то, что логику надо вынести в NavigationTreeNode?
> https://github.com/rsdn/janus/blob/d28a924a66c1ebd4f88415abca37b901d819e321/Janus-Common/CoreServices/NavigationTree/NavigationTreeNode.cs#L77
> 
> Ещё какие-то пожелания будут?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rsdn/janus/issues/1#issuecomment-123586154.

## 

With best regards,
  Andrew Koryavchenko, Visual C# MVP [Architecture].

**Comment by ViIvanov** [comment]
Там штука такая. Кто-то добавил (или начал добавлять?) видимо новые интерфейсы для нод - [INavigationTreeNode](https://github.com/rsdn/janus/blob/d28a924a66c1ebd4f88415abca37b901d819e321/Janus-Model/CoreServices/NavigationTree/INavigationTreeNode.cs) и добавил туда поддержку драг-дропа.

Нужно ли как-то эти интерфейсы реализовать в имеющихся нодах? Классах Forum, ForumFolder, FavoritesFeature и OutboxFeature? Или можно считать, что если кто-то так тот рефакторинг не доделал, то можно на него внимание не обращать?

Остался ли свн-сервер? Что бы историю посмотреть, кто и когда там что-то менял и с какими комментариями?

**Comment by andrewvk** [comment]
Я уже не помню кто там и что с драгндропом делал, но суть требуемых
изменений такова: нужно вынести дерево в плагинную модель. Там сейчас,
емнип, какой то промежуточный недоделанный вариант имени Влада.
СВН нет, не остался.

2015-07-27 0:45 GMT+03:00 Viacheslav Ivanov notifications@github.com:

> Там штука такая. Кто-то добавил (или начал добавлять?) видимо новые
> интерфейсы для нод - INavigationTreeNode
> https://github.com/rsdn/janus/blob/d28a924a66c1ebd4f88415abca37b901d819e321/Janus-Model/CoreServices/NavigationTree/INavigationTreeNode.cs
> и добавил туда поддержку драг-дропа.
> 
> Нужно ли как-то эти интерфейсы реализовать в имеющихся нодах? Классах
> Forum, ForumFolder, FavoritesFeature и OutboxFeature? Или можно считать,
> что если кто-то так тот рефакторинг не доделал, то можно на него внимание
> не обращать?
> 
> Остался ли свн-сервер? Что бы историю посмотреть, кто и когда там что-то
> менял и с какими комментариями?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rsdn/janus/issues/1#issuecomment-125043299.

## 

With best regards,
  Andrew Koryavchenko, Visual C# MVP [Architecture].
